# All possible configuration settings should be present in this file with either a reasonable
# default/example value or null (empty).
#
# DON'T ADD *Confidential* IDs and keys to this file. Use local.yml which should not be committed!
#

isDev: true
server:
  port: 8888
  # whether this connects via https
  secure: false
  key:
  cert:
  password:
  # 'basic' to use stunservers & turnservers config values
  # 'twilio' to use twilio stun and turn servers
  stunTurnServers: basic
rooms:
  # maximum number of clients per room. 0 = no limit
  maxClients: 0
stunservers:
  -
    urls: 'stun:stun.l.google.com:19302'
turnorigins:
turnservers: []
twilio:
  id:
  token:
